[package]
name = "ecu_diagnostics"
version = "0.90.61"
authors = ["Ashcon Mohseninia <ashconm@outlook.com>"]
edition = "2021"
description = "A rust crate for ECU diagnostic servers and communication APIs"
license = "MIT"
repository = "https://github.com/rnd-ash/ecu_diagnostics"
readme = "README.md"
keywords = ["socketcan", "kwp2000", "uds", "j2534", "dpdu"]
exclude = [
    "examples/*",
    "build.rs",
    "ecu_diagnostics.hpp"
]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "i686-pc-windows-msvc", "x86_64-apple-darwin"]

[workspace]
members = [
    "ffi",
]

[features]
default = ["passthru", "socketcan"]
socketcan = ["dep:socketcan-isotp", "dep:socketcan"]
passthru = ["dep:libloading", "dep:shellexpand", "dep:winreg", "dep:serde_json", "dep:j2534_rust"]


[dependencies]
auto_uds = "0.3"
j2534_rust = { version = "1.5.0", optional = true }
serde_json = { version = "1.0.79", optional = true }
libloading = { version = "0.7.3", optional = true }
log="0.4.16"
strum = "0.24"
strum_macros = "0.24"

[target.'cfg(windows)'.dependencies]
winreg = { version = "0.10.1", optional = true }

[target.'cfg(unix)'.dependencies]
shellexpand = { version = "2.1.0", optional = true }
#socketcan-isotp = { version = "1.0.0", optional = true }
socketcan-isotp = { optional = true, version = "1.0.1" }
socketcan = { version = "1.7.0", optional = true }
