name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build No Features
      run: cargo build --verbose --no-default-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build and test FFI
      run: |
        cargo build --verbose --package ecu_diagnostics_ffi --no-default-features
        cargo build --verbose --package ecu_diagnostics_ffi
        cargo test --verbose --package ecu_diagnostics_ffi
